[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "https://site-eig-v2.netlify.app"
  to = "https://eig.etalab.gouv.fr"
  status = 301
  force = true
