backend:
  name: git-gateway
  branch: develop

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "defis" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projets" # Used in the UI, ie.: "New Post"
    label_singular: "Projet"
    folder: "site/content/defis" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Administration", name: "who", widget: "string"}
      - {label: "Thématiques", name: "themes", widget: "relation", collection: "themes", multiple: true, value_field: "title", search_fields: ["title"]}
      # - {label: "Thématique", name: "themes", widget: "select", multiple: true, options: ["Sécurité", "Ecologie", "Education", "Ressources humaines", "Citoyenneté", "Formation", "Numérique public", "Service public", "Santé", "Santé-Environnement", "Justice", "Protection sociale"]}
      - {label: "Promotion", name: "promos", widget: "select", multiple: true, options: ["EIG 1", "EIG 2", "EIG 3", "EIG 4"]}
      - {label: "Lieu", name: "town", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Expertises", name: "expertises", widget: "relation", collection: "expertises", multiple: true, value_field: "title", search_fields: ["title"]}
      # - {label: "Expertises", name: "expertises", widget: "select", multiple: true, options: ["Data Engineering", "Data science", "Design", "Développement", "Géomatique", "Juriste"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "personnes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Personnes" # Used in the UI, ie.: "New Post"
    label_singular: "Personne"
    folder: "site/content/personnes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Poste", name: "job", widget: "string"}
      - {label: "Promotion", name: "promos", widget: "select", multiple: true, options: ["EIG 1", "EIG 2", "EIG 3", "EIG 4"]}
      - {label: "Rôle", name: "role", widget: "select", options: [{label: "Participant", value: "participant"}, {label: "Agent du programme", value: "agent-programme"}, {label: "Agent de l’écosystème", value: "agent-ecosysteme"}]}
      - {label: "Défi", name: "defi", widget: "relation", collection: "defis", value_field: "title", search_fields: ["title"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Linkedin", name: "linkedin", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "themes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Thématiques" # Used in the UI, ie.: "New Post"
    label_singular: "Thématique"
    folder: "site/content/themes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string"}
  - name: "expertises" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Expertises" # Used in the UI, ie.: "New Post"
    label_singular: "Expertise"
    folder: "site/content/expertises" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Homepage"
        name: "home"
        fields:
          - {label: "Hero", name: "hero", widget: "object", fields: [{label: Title, name: title, widget: text}, {label: Bouton, name: btn, widget: object, fields: [{label: Title, name: title, widget: string}, {label: URL, name: url, widget: string}]}]}
          - {label: Défis, name: defis, widget: object, fields: [{label: Sous-titre, name: sub, widget: string}, {label: Description, name: desc, widget: text}]}
          - {label: Talents, name: talents, widget: object, fields: [{label: Sous-titre, name: sub, widget: string}, {label: Description, name: desc, widget: text}]}
          - {label: Agents, name: agents, widget: object, fields: [{label: Sous-titre, name: sub, widget: string}, {label: Description, name: desc, widget: text}]}
          - {label: Rejoindre, name: join, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Titre, name: title, widget: string}, {label: Sous-titre, name: sub, widget: string}, {label: Bouton, name: btn, widget: object, fields: [{label: Title, name: title, widget: string}, {label: URL, name: url, widget: string}]}]}
          - {label: Médias, name: medias, widget: object, fields: [{label: Description, name: desc, widget: text}, {label: Tuiles, name: tiles, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Title, name: title, widget: string}]}]}
      - file: "site/content/personal-data.md"
        label: "Données personnelles"
        name: "personal-data"
        fields:
          - {label: "Titre", name: title, widget: string}
          - {label: "Contenu", name: "body", widget: "markdown"}
      - file: "site/content/cookies.md"
        label: "Gestion des cookies"
        name: "cookies"
        fields:
          - {label: "Titre", name: title, widget: string}
          - {label: "Contenu", name: "body", widget: "markdown"}
      - file: "site/content/impact.md"
        label: "Impact"
        name: "impact"
        fields:
          - {label: Titre, name: title, widget: string}
          - {label: Description, name: desc, widget: text}
      - file: "site/content/team.md"
        label: "Equipe"
        name: "team"
        fields:
          - {label: Titre, name: title, widget: string}
          - {label: Description, name: desc, widget: text}
          